### ISSUE TITLE
Needs pom dependency updates

### ISSUE THREAD

**Issue by kephale** [PreibischLab/RS-FISH#11]
I was working pushing to the update site in response to @LauraBreimann's request.

It looks like RS-FISH is falling behind on versions:

```
[INFO] Uploading 38 (removing 91) to RadialSymmetry (webdav:RadialSymmetry:<password>:./)

[ERROR] There are conflicts:

jars/jaxb-api-2.3.0.jar: Is not installed but a dependency of

jars/scijava-common-2.87.1.jar

jars/scijava-common-2.87.1.jar: Depends on jars/jaxb-api.jar which is about to be removed.
```

This is also an older scijava-common and made me notice that the pom-scijava version needs to be updated. I haven't started this and am putting this on my queue. It might be a quick job but in case someone wants to take care of it before I do, I'm posting this issue.

**Comment by LauraBreimann** [comment]
Thank you @kephale! 
Maybe @mzouink could have a look at these conflicts?

**Comment by kephale** [comment]
Great, thank you @mzouink.

For some reason jitpack doesn't like the maven release flag: https://jitpack.io/com/github/PreibischLab/RS-FISH/e9db74a/build.log

The trivial fix is in this branch: https://github.com/PreibischLab/RS-FISH/tree/remove-maven-release-flag and it looks like it works: https://jitpack.io/com/github/PreibischLab/RS-FISH/742f6a3/build.log

It looks like the everything works from there. If you merge that branch or undo the release flag in the pom, then I can point to the latest `main` branch. Otherwise, it is still using the same code anyway.

**Comment by LauraBreimann** [comment]
The updated version seems to work for the normal RS-FISH function and the newly added Mask filtering. 

However @StephanPreibisch added some spot intensity refinement back in January (bc19ed231394bfe49cbbc9f33b1d36acb81e83b3) and if I select that it throws an exception. 
<img width="348" alt="Screenshot 2022-05-19 at 01 24 34" src="https://user-images.githubusercontent.com/17985806/169217446-eeb38fad-61a7-475a-83a1-858190f587a8.png">
 `java.lang.ArrayIndexOutOfBoundsException`
