### ISSUE TITLE
How to adjust sigma and threshold

### ISSUE THREAD

**Issue by buttf7** [PreibischLab/RS-FISH#12]
Could a brief explanation on the definition for the sigma and threshold parameters are for spot detection be provided? And how they can be used to optimize detection?

**Comment by LauraBreimann** [comment]
Hi there, 
I added a new section ([330a23bba9ec10c9883be2f134e34b6222252b46](https://github.com/PreibischLab/RS-FISH/commit/330a23bba9ec10c9883be2f134e34b6222252b46)) on how to choose the different parameters and added a little overview image. Hope this helps! Pls, let us know if you still have questions.

**Comment by LauraBreimann** [comment]
Yes exactly, sigma is the size of the detected spots. There is a limit on how to set the slider in the interactive mode, but switching to advanced mode smaller and larger values can be chosen (not sure if there is a limit to this). But for most cases that we tested, we could set all values using the sliders. 
For non-homogenous spot sizes, it depends a bit on how different the spots are. Typically spots don't have to be exactly the same size to be detected but if the difference is very large it might be useful to detect spots in several rounds with different parameters (maybe scripting this could be really helpful here) and then combine the results.

**Comment by buttf7** [comment]
![RNA_1to10_processed](https://user-images.githubusercontent.com/103357482/175096912-ac49e9eb-4572-4b85-9795-f332c4857f29.jpg)

Hello, I have provided a sample image. Thank you for all your help.

**Comment by LauraBreimann** [comment]
Ok couple of questions: is the image normally a z-stack or is it 2D? I see the file is a jpg, do you also have a tiff version of this image? Would it be possible to upload a tiff version of this via google drive or dropbox and provide a link? Then it is much easier for me to help you! But looking at the image we should be able to find good parameters to detect all spots!

**Comment by buttf7** [comment]
Hello! Let me know if this works. https://drive.google.com/file/d/18A06Q_YBMry5Lhoqt3anYcJ_fET7s22c/view?usp=sharing

**Comment by buttf7** [comment]
Thank you, that looks great. Is there a way to further minimize false positive detections. Also, would you suggest the multiple layer detection approach.

**Comment by LauraBreimann** [comment]
So in the above image, I wouldn't call them false positives as I can see signals at each location, but if you only want to detect brighter spots, the intensity threshold can be used to only select spots with higher intensity. When I use the tool I always zoom in really close to one area (for instance one cell) and see what is detected. So I would draw the box for pre detection very small and move it around to really check how the detection looks like. I recorded a little video on how I normally check my image (I used a max projection here, but the same process for the full stack): https://drive.google.com/file/d/1Rwl7Uq-vHoT4-xbsdDvpKB5Q--mJyHeD/view?usp=sharing

**Comment by buttf7** [comment]
Is it more difficult to perform the full stack spot detection, I cannot find parameters that appear to detect at even the values that you have provided.
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/103357482/176203292-9c2e1e34-5de6-40ba-94d9-b364ed4985f0.png">
